### ISSUE TITLE
Can load plugin, evenghost not responding

### ISSUE THREAD

**Issue by jolled** [marcushultman/eventghost-lifx#1]
Hi, 

I try to add this plugin to EventGhost (running on windows 10) but it fails. EventGhost just go in to not responing state. 

**I updated eventghost to the latest release and now it works**

(i can load other plugins without problems)

Regards
Markus

**Comment by marcushultman** [comment]
Hi,

Great to hear that it works. Just drop a comment if you're having any trouble.

/Marcus

**Comment by topic2k** [comment]
I've created a PR with fixes for the above error: #3
